@apiBaseUrl = http://localhost:3000/api
@token=eyJ

### Afficher toutes les catégories
GET {{apiBaseUrl}}/categories

### Afficher une catégorie
GET {{apiBaseUrl}}/categories/:id

### Créer une catégorie
POST {{apiBaseUrl}}/admin/categories

### Update catégorie
PATCH {{apiBaseUrl}}/admin/categories/:id
Content-Type: application/json

{
  "name": "Burgers"
}

### Delete une catégorie
PATCH {{apiBaseUrl}}/admin/categories/:id
