@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MzEzMjEzNCwiZXhwIjoxNzYzMTM1NzM0fQ.05p7NpGTweP3_kHecTqhFqzqVdGSBvZmZ4Hl05cD5TY

### Lister toutes les recettes
GET {{apiBaseUrl}}/recipes

### Voir une recette par ID
GET {{apiBaseUrl}}/recipes/16

### Créer une recette (user)
POST {{apiBaseUrl}}/recipes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "la purrée de star wars",
  "category_id": 1,
  "movie_id": 33,
  "number_of_person": 3,
  "preparation_time": 45,
  "image": "http://example.com/donuts-roses.jpg",
  "description": "Les délicieux donuts roses préférés d'Homer Simpson, inspirés du film.",
  "ingredients": "Farine\nSucre\nBeurre\nLait\nLevure\nColorant rose\nVermicelles",
  "preparation_steps": "Préparer la pâte\nFormer les donuts\nFaire frire\nAjouter le glaçage rose\nDécorer avec des vermicelles",
  "status": "published"
}

### Supprimer une recette (user)
DELETE {{apiBaseUrl}}/recipes/7
Authorization: Bearer {{token}}
