@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MzYzNTA3OCwiZXhwIjoxNzYzNjM4Njc4fQ.gj9bOHUi84Btp0W6uAFkOkanMYiuWFSuLJ1U8EU2pfM

### Connexion ###
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password"
}

### Créer une recette (avec upload image)
POST {{apiBaseUrl}}/recipes
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="title"

tajine
--boundary123
Content-Disposition: form-data; name="category_id"

2
--boundary123
Content-Disposition: form-data; name="movie_id"

222
--boundary123
Content-Disposition: form-data; name="number_of_person"

1
--boundary123
Content-Disposition: form-data; name="preparation_time"

30
--boundary123
Content-Disposition: form-data; name="description"

sandwich au poulet epice
--boundary123
Content-Disposition: form-data; name="ingredients"

Pain
viande
Sel
--boundary123
Content-Disposition: form-data; name="preparation_steps"

Éplucher
Cuire
Écraser
Assaisonner
--boundary123
Content-Disposition: form-data; name="status"

published
--boundary123
Content-Disposition: form-data; name="image"; filename="Macarons.jpg"
Content-Type: image/jpeg

< ../tajine.webp
--boundary123--

### Modifier une recette (avec upload image) ###
PATCH {{apiBaseUrl}}/recipes/me/26
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=update123

--update123
Content-Disposition: form-data; name="title"

Tarte au citron modifiée
--update123
Content-Disposition: form-data; name="category_id"

3
--update123
Content-Disposition: form-data; name="movie_id"

557
--update123
Content-Disposition: form-data; name="number_of_person"

4
--update123
Content-Disposition: form-data; name="preparation_time"

45
--update123
Content-Disposition: form-data; name="description"

Une tarte modifiée avec amour.
--update123
Content-Disposition: form-data; name="ingredients"

Citron
Oeufs
Sucre
Pâte sablée
--update123
Content-Disposition: form-data; name="preparation_steps"

Mélanger
Cuire
Refroidir
--update123
Content-Disposition: form-data; name="status"

published
--update123
Content-Disposition: form-data; name="image"; filename="nouvelle-image.jpg"
Content-Type: image/jpeg

< ../kebab.webp
--update123--

### Créer un brouillon
POST {{apiBaseUrl}}/recipes/draft
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=draft4

--draft4
Content-Disposition: form-data; name="title"

Ma recette brouillon
--draft4--