@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MjQ0Nzc4NSwiZXhwIjoxNzYyNDUxMzg1fQ.RvV-aYXTvDW2IYK_Oc1p4yUmdkRlQUgd0Pr4_7GqQdo
# ========================
# AUTHENTIFICATION
# ========================

### Inscription ###
POST {{apiBaseUrl}}/users
Content-Type: application/json

{
  "username": "loic",
  "email": "loic@example.com",
  "password": "loic",
  "confirm_password": "loic",
  "age_declaration": true,
  "cgu_accepted": true
}

### Connexion ###
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "bob@example.com",
  "password": "bob"
}

### Mon profil ###
GET {{apiBaseUrl}}/auth/me
Authorization: Bearer {{token}}


### Modifier son mot de passe (user ou admin) ###
PATCH {{apiBaseUrl}}/users/me/password/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "mehdi",
  "newPassword": "mehdi"
}

### Supprimer son compte ###
DELETE {{apiBaseUrl}}/users/me
Authorization: Bearer {{token}}


# ========================
# ADMIN
# ========================

### Lister tous les utilisateurs (admin) ###
GET {{apiBaseUrl}}/users
Authorization: Bearer {{token}}

### Modifier le rôle d’un utilisateur (admin) ###
PATCH {{apiBaseUrl}}/users/12
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "role": "admin"
}

### Supprimer un utilisateur (admin) ###
DELETE {{apiBaseUrl}}/users/13
Authorization: Bearer {{token}}


# ========================
# CATEGORIES
# ========================

### Lister toutes les catégories
GET {{apiBaseUrl}}/categories

### Créer une catégorie (admin)
POST {{apiBaseUrl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Entrée"
}

# ========================
# RECIPES
# ========================

### Lister toutes les recettes
GET {{apiBaseUrl}}/recipes

### Voir une recette par ID
GET {{apiBaseUrl}}/recipes/1

### Créer une recette (user)
POST {{apiBaseUrl}}/recipes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Pizza maison",
  "category_id": 1,
  "movie_id": 1234,
  "number_of_person": 2,
  "preparation_time": 40,
  "description": "Une pizza inspirée du film Ratatouille 🍕",
  "ingredients": "pâte, tomate, fromage",
  "preparation_steps": "Pétrir, garnir, cuire",
  "status": "draft"
}

### Supprimer une recette (user)
DELETE {{apiBaseUrl}}/recipes/1
Authorization: Bearer {{token}}
