@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MjQzNzA1NiwiZXhwIjoxNzYyNDQwNjU2fQ.YrlF7ssHf4ggSvDlu7KxWapYrSHgMPVHgx4yReH9r54
# ========================
# AUTHENTIFICATION
# ========================

### Inscription
POST {{apiBaseUrl}}/auth/register
Content-Type: application/json

{
  "username": "mehdi",
  "email": "mehdi@example.com",
  "password": "mehdi123",
  "confirm_password": "mehdi123",
  "age_declaration": true,
  "cgu_accepted": true
}

### Connexion
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "mehdi@example.com",
  "password": "mehdi123"
}

### Mon profil
GET {{apiBaseUrl}}/auth/me
Authorization: Bearer {{token}}


# ========================
# USERS
# ========================

### Modifier son mot de passe (user ou admin)
PATCH {{apiBaseUrl}}/auth/me/password/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "mehdi123",
  "newPassword": "mehdi"
}

### Supprimer son compte
DELETE {{apiBaseUrl}}/auth/me
Authorization: Bearer {{token}}


# ========================
# ADMIN
# ========================

### Lister tous les utilisateurs (admin)
GET {{apiBaseUrl}}/admin/users
Authorization: Bearer {{token}}

### Modifier le rôle d’un utilisateur (admin)
PATCH {{apiBaseUrl}}/admin/users/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "role": "admin"
}

### Supprimer un utilisateur (admin)
DELETE {{apiBaseUrl}}/users/3
Authorization: Bearer {{token}}


# ========================
# CATEGORIES
# ========================

### Lister toutes les catégories
GET {{apiBaseUrl}}/categories

### Créer une catégorie (admin)
POST {{apiBaseUrl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Entrée"
}

# ========================
# RECIPES
# ========================

### Lister toutes les recettes
GET {{apiBaseUrl}}/recipes

### Voir une recette par ID
GET {{apiBaseUrl}}/recipes/1

### Créer une recette (user)
POST {{apiBaseUrl}}/recipes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Pizza maison",
  "category_id": 1,
  "movie_id": 1234,
  "number_of_person": 2,
  "preparation_time": 40,
  "description": "Une pizza inspirée du film Ratatouille 🍕",
  "ingredients": "pâte, tomate, fromage",
  "preparation_steps": "Pétrir, garnir, cuire",
  "status": "draft"
}

### Supprimer une recette (user)
DELETE {{apiBaseUrl}}/recipes/1
Authorization: Bearer {{token}}
