@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MjUzNjU3NywiZXhwIjoxNzYyNTQwMTc3fQ.DLDw1xWOWKN29qdhFGbpj7flOXQL7CFAF3eLQeOz8WU
# ========================
# AUTHENTIFICATION
# ========================

### Inscription ###
POST {{apiBaseUrl}}/users
Content-Type: application/json

{
  "username": "loic",
  "email": "loic@example.com",
  "password": "loic",
  "confirm_password": "loic",
  "age_declaration": true,
  "cgu_accepted": true
}

### Connexion ###
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
  "email": "bob@example.com",
  "password": "bob"
}

### Mon profil ###
GET {{apiBaseUrl}}/auth/me
Authorization: Bearer {{token}}


### Modifier son mot de passe (user ou admin) ###
PATCH {{apiBaseUrl}}/users/me/password/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "mehdi",
  "newPassword": "mehdi"
}

### Supprimer son compte ###
DELETE {{apiBaseUrl}}/users/me
Authorization: Bearer {{token}}


# ========================
# ADMIN
# ========================

### Lister tous les utilisateurs (admin) ###
GET {{apiBaseUrl}}/users
Authorization: Bearer {{token}}

### Modifier le rôle d’un utilisateur (admin) ###
PATCH {{apiBaseUrl}}/users/12
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "role": "admin"
}

### Supprimer un utilisateur (admin) ###
DELETE {{apiBaseUrl}}/users/13
Authorization: Bearer {{token}}


# ========================
# CATEGORIES
# ========================

### Lister toutes les catégories ###
GET {{apiBaseUrl}}/categories

### Créer une catégorie (admin) ###
POST {{apiBaseUrl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "glace"
}
### Supprimer une catégorie (admin) ###
DELETE {{apiBaseUrl}}/categories/4
Authorization: Bearer {{token}}

# ========================
# RECIPES
# ========================

### Lister toutes les recettes sauf draft ###
GET {{apiBaseUrl}}/recipes

### Voir une recette par ID sauf draft
GET {{apiBaseUrl}}/recipes/1

### Lister mes recettes ###
GET {{apiBaseUrl}}/recipes/me
Authorization: Bearer {{token}}

### Voir ma recette ###
GET {{apiBaseUrl}}/recipes/me/1
Authorization: Bearer {{token}}

### Créer une recette (user)
POST {{apiBaseUrl}}/recipes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "souppe",
  "category_id": 2,
  "movie_id": 1234,
  "number_of_person": 2,
  "image":"http:kjijp",
  "preparation_time": 40,
  "description": "raclette",
  "ingredients": "fabien",
  "preparation_steps": "rouler",
  "status": "published"
}

### Modifier n'importe qu'elle recette (admin)
PATCH {{apiBaseUrl}}/recipes/6
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "souppe au choux",
  "category_id": 2,
  "movie_id": 1234,
  "number_of_person": 2,
  "image":"http:kjijp",
  "preparation_time": 40,
  "description": "raclette",
  "ingredients": "fabien",
  "preparation_steps": "rouler",
  "status": "published"
}

### Supprimer une recette (user)
DELETE {{apiBaseUrl}}/recipes/1
Authorization: Bearer {{token}}
