@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyMzQ5ODY0LCJleHAiOjE3NjIzNTM0NjR9._VjwN-BJVJKoVUZsPODXOsFOt8s6nC77sIUruS-RouI
### Afficher toutes les utilisateurs
GET {{apiBaseUrl}}/users

### Inscription 
POST {{apiBaseUrl}}/auth/register
Content-Type:application/json

{
  "username": "ludoo",
  "email": "ludoo@example.com",
  "password": "ludo",
  "confirm_password":"ludo",
  "age_declaration": true,
  "cgu_accepted":true
}

### Connexion
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
  "email":"ludo@example.com",
  "password":"ludo"
}

### Mon profil 
GET {{apiBaseUrl}}/auth/me
Authorization: Bearer {{token}}