@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyMzU3MzU1LCJleHAiOjE3NjIzNjA5NTV9.as7XmqtxfqkK3YvEQCms6buSdNjStEE1ogzvut-RMCs
@token_admin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MjM3MDI0OSwiZXhwIjoxNzYyMzczODQ5fQ.hAbdIX5sE26s7vit5I5E7ws65imYLFfW5H1-01mdZok
GET {{apiBaseUrl}}/users
Authorization: Bearer {{token_admin}}
### Inscription 
POST {{apiBaseUrl}}/auth/register
Content-Type:application/json

{
  "username": "bob",
  "email": "bob@example.com",
  "password": "bob",
  "confirm_password":"bob",
  "age_declaration": true,
  "cgu_accepted":true
}

### Connexion
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
  "email":"bob@example.com",
  "password":"bob"
}

### Mon profil 
GET {{apiBaseUrl}}/auth/me
Authorization: Bearer {{token_admin}}

### Modifier le role d'un utilisateur (Admin)
PATCH {{apiBaseUrl}}/users/2
Authorization: Bearer {{token_admin}}
Content-Type: application/json

{
  "role":"user"
}

### Supprimer un user (Admin)
DELETE {{apiBaseUrl}}/users/7
Authorization: Bearer {{token_admin}}
