@apiBaseUrl = http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MjQyNDEzNCwiZXhwIjoxNzYyNDI3NzM0fQ.K7_S32iajLZUHCuiloXtbShmhYgWnprxESgTdFqYXY0
@token_admin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MjQyNDEzNCwiZXhwIjoxNzYyNDI3NzM0fQ.K7_S32iajLZUHCuiloXtbShmhYgWnprxESgTdFqYXY0
GET {{apiBaseUrl}}/users
Authorization: Bearer {{token}}
### Inscription 
POST {{apiBaseUrl}}/auth/register
Content-Type:application/json

{
  "username": "julien",
  "email": "julien@example.com",
  "password": "julien",
  "confirm_password":"julien",
  "age_declaration": true,
  "cgu_accepted":true
}

### Connexion
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
  "email":"bob@example.com",
  "password":"bob"
}

### Mon profil 
GET {{apiBaseUrl}}/auth/me
Authorization: Bearer {{token}}

### Modifier le role d'un utilisateur (Admin)
PATCH {{apiBaseUrl}}/users/1
Authorization: Bearer {{token_admin}}
Content-Type: application/json

{
  "role":"user"
}

### Supprimer un user (Admin)
DELETE {{apiBaseUrl}}/users/8
Authorization: Bearer {{token_admin}}
